fix: missed update to the merge-release script

diff --git a/bin/merge-release b/bin/merge-release
--- a/bin/merge-release
+++ b/bin/merge-release
@@ -41,7 +41,7 @@ git push origin $MAIN_BRANCH || { echo -e "\e[31mError: Failed to push updated '
 if [[ $BRANCH_TYPE == "hotfix" ]]; then
     git checkout develop || { echo -e "\e[31mError: Failed to checkout 'develop' branch"; exit 1; }
     git rebase || { echo -e "\e[31mError: Failed to rebase 'develop' branch"; exit 1; }
-    git merge --ff-only "origin/$TARGET_BRANCH" || git merge --no-ff "origin/$TARGET_BRANCH" -m "Merged branch '$TARGET_BRANCH' into develop" || { echo -e "\e[31mError: Failed to merge 'main' into $CURRENT_BRANCH"; exit 1; }
+    git merge --ff-only "origin/$TARGET_BRANCH" || git merge --no-ff "origin/$TARGET_BRANCH" -m "chore: Merged branch '$TARGET_BRANCH' into develop" || { echo -e "\e[31mError: Failed to merge 'main' into $CURRENT_BRANCH"; exit 1; }
     git push origin develop || { echo -e "\e[31mError: Failed to push updated $CURRENT_BRANCH branch to origin"; exit 1; }
 fi
 
